server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker-logs
  static_configs:
  - targets: [localhost]
    labels:
      job: docker-logs
      __path__: /var/lib/docker/containers/*/*-json.log

  pipeline_stages:
  - json:
      expressions:
        log: log
        stream: stream
        time: time
  - labels:
      stream:
  - timestamp:
      source: time
      format: RFC3339Nano
  - output:
      source: log

  relabel_configs:
  - source_labels: [__path__]
    regex: .*/([0-9a-f]{64})/.*-json\.log
    target_label: container_id
