services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ../env/.env.db_prod
    ports:
      - "5432:5432"
    volumes:
      - kindle_prod_data:/var/lib/postgresql/data
    networks:
      - internal

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    restart: always
    depends_on:
      - db
    env_file:
      - ../env/.env.db_prod
      - ../env/.env.auth
    ports:
      - "8000:8000"
    networks:
      - internal
      - public

  nginx:
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../static:/static:ro
      - ../ssl:/etc/nginx/ssl:ro
    networks:
      - public

  loki:
    image: grafana/loki:2.9.8
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ../loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - internal

  promtail:
    image: grafana/promtail:2.9.8
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - internal

  grafana:
    image: grafana/grafana:11.3.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ../grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ../grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"
    networks:
      - internal
      - public

volumes:
  kindle_prod_data:
  loki_data:
  grafana_data:

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
