services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ../env/.env.db_prod
    ports:
      - "5432:5432"
    volumes:
      - kindle_prod_data:/var/lib/postgresql/data
    networks:
      - internal

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    restart: always
    depends_on:
      - db
    env_file:
      - ../env/.env.db_prod
      - ../env/.env.auth
    ports:
      - "8000:8000"
    networks:
      - internal
      - public

  nginx:
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../static:/static:ro
    networks:
      - public

volumes:
  kindle_prod_data:

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
