"""auto revision

Revision ID: 98200438bb25
Revises: b7455970e754
Create Date: 2025-08-16 15:43:34.340596

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "98200438bb25"
down_revision: Union[str, Sequence[str], None] = "b7455970e754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
