"""Fix bio

Revision ID: 9e13699b3dd1
Revises: e743a06a7ea7
Create Date: 2025-08-15 12:58:44.139876

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9e13699b3dd1'
down_revision: Union[str, Sequence[str], None] = 'e743a06a7ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
