"""auto revision

Revision ID: b7455970e754
Revises: 7ad54cb4a363
Create Date: 2025-08-16 14:25:26.526274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7455970e754"
down_revision: Union[str, Sequence[str], None] = "7ad54cb4a363"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hash_password",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=60),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hash_password",
        existing_type=sa.String(length=60),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
